import { Outfit } from 'next/font/google'
import './assets/scss/main.scss'
import './assets/scss/variables.scss'

const outfit = Outfit({ 
    weight: ['300', '700'],
    style: ['normal'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
  title: 'Events App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={outfit.className}>
            <main >
                {children}
            </main>
        </body>
    </html>
  )
}
